run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    # TODO: enable one by one
    - promlinter
    - errname
    - godox
    - contextcheck
    - predeclared
    - misspell
    - nakedret
    - exhaustive
    - tparallel
    - revive
    - goimports
    - ineffassign
    - gci
    - paralleltest
    - maintidx
    - unparam
    - goconst
    - wastedassign
    - gosimple
    - dupl
    - unused
    - nestif
    - deadcode
    - varcheck
    - errorlint
    - lll
    - nilnil
    - gocyclo
    - prealloc
    - bodyclose
    - whitespace
    - gofumpt
    - godot
    - gocritic
    - gocognit
    - unconvert
    - errchkjson
    - thelper
    - ireturn
    - forbidigo
    - tagliatelle
    - cyclop
    - errcheck
    - exhaustivestruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gomnd
    - gosec
    - varnamelen
    - wrapcheck
    - noctx
    - staticcheck
    - stylecheck
    - golint
    - interfacer 
    - maligned    
    - nlreturn    
    - scopelint   
    - testpackage 
    - wsl
    - ifshort
