# for github.com
approvals:
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - "zalando"
# mandatory pull request labels
pull-request:
  labels:
    additional: true
    oneOf:
      - architectural
      - major
      - minor
      - bugfix
      - documentation
      - dependencies
X-Zalando-Team: "teapot"
