version: "2017-09-20"
pipeline:
- id: build
  overlay: ci/golang
  type: script
  commands:
  - desc: build-push
    cmd: |
      if [[ $CDP_TARGET_BRANCH == master && ! $CDP_PULL_REQUEST_NUMBER ]]; then
        RELEASE_VERSION="$(git describe --tags --always --dirty)"
        IMAGE="registry-write.opensource.zalan.do/pathfinder/skipper:${RELEASE_VERSION}"
      else
        IMAGE="registry-write.opensource.zalan.do/pathfinder/skipper-test:${CDP_BUILD_VERSION}"
      fi
      export IMAGE
      make deps shortcheck
      git status
      git diff
      cd packaging && make docker-build && git status && git diff && make docker-push
- id: build-docs
  type: script
  when:
    event: pull_request
  commands:
    - desc: Install mkdocs dependecies
      cmd: |
        apt-get update && apt-get install python3-pip -y
        pip3 install mkdocs mkdocs-cinder
    - desc: Build the skipper docs
      cmd: |
        mkdocs build
    - desc: Upload the docs
      cmd: |
        mkdocs gh-deploy

