{
 "title": "Skipper Operational Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Status Codes",
   "type": "graph",
   "description": "2xx, 4xx & 5xx Status Code Rates Skipper is returning",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(skipper_response_duration_seconds_count{code =~ \"2.*\"}[1m])) by (code)",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(skipper_response_duration_seconds_count{code =~ \"4.*\"}[1m])) by (code)",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(skipper_response_duration_seconds_count{code =~ \"5.*\"}[1m])) by (code)",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "P99 Backend Latency",
   "type": "graph",
   "description": "P99 Latency for backends Skipper is routing to",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(skipper_serve_host_duration_seconds_bucket{}[1m])) by (le, host))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "P99 Request Filter Duration",
   "type": "graph",
   "description": "Note: The promql query may require a label selector on Kubernetes, see https://opensource.zalando.com/skipper/operation/operation/#prometheus for details.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(skipper_filter_request_duration_seconds_bucket{}[1m])) by (le) )"
    }
   ]
  },
  {
   "title": "P99 Response Filter Duration",
   "type": "graph",
   "description": "Note: The promql query may require a label selector on Kubernetes, see https://opensource.zalando.com/skipper/operation/operation/#prometheus for details.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(skipper_filter_response_duration_seconds_bucket{}[1m])) by (le) )"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Max Go Routines. Note: The promql query may require a label selector on Kubernetes, see https://opensource.zalando.com/skipper/operation/operation/#prometheus for details.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(go_goroutines{})", "legendFormat": "goroutines" }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "description": "Max Go Threads. Note: The promql query may require a label selector on Kubernetes, see https://opensource.zalando.com/skipper/operation/operation/#prometheus for details.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(go_threads{})", "legendFormat": "go_threads" }
   ]
  },
  {
   "title": "Heap",
   "type": "graph",
   "description": "Max heap memory in use in MB. Note: The promql query may require a label selector on Kubernetes, see https://opensource.zalando.com/skipper/operation/operation/#prometheus for details.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "max(go_memstats_heap_inuse_bytes{}) / 1024 / 1000",
     "legendFormat": "Heap Size"
    }
   ]
  },
  {
   "title": "No. of Heap Objects ",
   "type": "graph",
   "description": "Max number of heap objects. Note: The promql query may require a label selector on Kubernetes, see https://opensource.zalando.com/skipper/operation/operation/#prometheus for details.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(go_memstats_heap_objects{})",
     "legendFormat": "No. of Heap Objects "
    }
   ]
  },
  {
   "title": "P75 Go GC Runtime",
   "type": "graph",
   "description": "Max of P75 Go GC runtime in ms. Note: The promql query may require a label selector on Kubernetes, see https://opensource.zalando.com/skipper/operation/operation/#prometheus for details.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(go_gc_duration_seconds{quantile=\"0.75\"}) * 1000 * 1000"
    }
   ]
  }
 ]
}