---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: {{ .Values.namespace }}
  labels:
    application: external-dns
    chart: {{ .Chart.Version }}
{{- if .Values.eks_iam }}
  annotations:
    eks.amazonaws.com/role-arn:
      arn:aws:iam::{{ .Values.awsAccountID }}:role/{{ .Values.external_dns.aws_role }}
{{- end }}
---
# allows to list services and ingresses
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
  labels:
    application: external-dns
    chart: {{ .Chart.Version }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns
  labels:
    application: external-dns
    chart: {{ .Chart.Version }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: {{ .Values.namespace }}
