{{ if .Values.kube_aws_iam_controller.enabled }}
apiVersion: zalando.org/v1
kind: AWSIAMRole
metadata:
  name: kube-ingress-aws-controller-aws-iam-credentials
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ .Chart.Version }}
spec:
  roleReference: {{ .Values.kube_ingress_aws_controller.aws_role }}
{{ end }}
