FROM --platform=linux/arm/v7 alpine@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978
LABEL maintainer="Team Gateway&Proxy @ Zalando SE <team-gwproxy@zalando.de>"
RUN apk --no-cache add ca-certificates && update-ca-certificates
ADD build/linux/arm/v7/skipper \
    build/linux/arm/v7/eskip \
    build/linux/arm/v7/webhook \
    build/linux/arm/v7/routesrv /usr/bin/
ENV PATH $PATH:/usr/bin

EXPOSE 9090 9911

CMD ["/usr/bin/skipper"]
