name: ci
on: [pull_request]
env:
  GO111MODULE: on
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14'
    - run: go version
    - run: make ci-trigger
