name: docs-ci

permissions: {}

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'docs/**'

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: 3.x
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs mkdocs-material markdown-include
      - run: mkdocs gh-deploy --force
