name: pr
on: [ pull_request ]
permissions:
  contents: read
env:
  TESTCONTAINERS_RYUK_DISABLED: true
jobs:
  semgrep:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      # Retrieve the source code for the repository
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      # Fetch the semgrep rules
      - run: git clone https://github.com/dgryski/semgrep-go.git
      # Run the rule checker using the fetched rules
      - run: semgrep ci -f semgrep-go

  check-race:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: "^1.23"
          check-latest: true
      - run: go version
      - run: make deps
      - run: make check-race
  tests_rest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: "^1.23"
          check-latest: true
      - run: go version
      - run: make deps
      - run: |
          : Check format
          make fmt
          git diff --exit-code
      - run: make vet
      - run: make staticcheck
      - run: make shortcheck_split1
  tests_.:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: "^1.23"
          check-latest: true
      - run: go version
      - run: make deps
      - run: |
          : Check format
          make fmt
          git diff --exit-code
      - run: make vet
      - run: make staticcheck
      - run: make shortcheck_split2
  tests_proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: "^1.23"
          check-latest: true
      - run: go version
      - run: make deps
      - run: |
          : Check format
          make fmt
          git diff --exit-code
      - run: make vet
      - run: make staticcheck
      - run: make shortcheck_split3
  tests_ratelimit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: "^1.23"
          check-latest: true
      - run: go version
      - run: make deps
      - run: |
          : Check format
          make fmt
          git diff --exit-code
      - run: make vet
      - run: make staticcheck
      - run: make shortcheck_split4
  tests_net:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: "^1.23"
          check-latest: true
      - run: go version
      - run: make deps
      - run: |
          : Check format
          make fmt
          git diff --exit-code
      - run: make vet
      - run: make staticcheck
      - run: make shortcheck_split5
